/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        // Player-facing system (auth, player app, public web) — orange/Figtree.
        player: {
          bg: "#FAF8F6",
          surface: "#FFFFFF",
          "surface-2": "#F4EFEC",
          border: "#E5DED8",
          "border-light": "#EBE5E1",
          ink: "#141A1D",
          "ink-muted": "#5C544D",
          "ink-faint": "#7A7068",
          "ink-fainter": "#9A9791",
          accent: "#EF5A2C",
          "accent-hover": "#C8431C",
          "accent-soft": "#FFF3EE",
          "accent-soft-border": "#F6DCD1",
          success: "#1F7A52",
          "success-soft": "#E4F0EA",
          "success-soft-border": "#A9CFBD",
          "success-dark": "#14563A",
          warn: "#8A5A0A",
          "warn-soft": "#FDF6E9",
          "warn-soft-border": "#F0DFBC",
          danger: "#A8432C",
          "danger-soft": "#F8E5E0",
          "danger-soft-border": "#DDBAB1",
          teal: "#0E6274",
          "teal-soft": "#EBF2F4",
        },
        // Owner/business-facing system (owner app, venue onboarding, admin, owner web) — teal/IBM Plex Sans.
        owner: {
          bg: "#F4F6F7",
          surface: "#FFFFFF",
          border: "#DCE3E6",
          "border-light": "#EDF1F2",
          ink: "#101C21",
          "ink-muted": "#5B7079",
          "ink-faint": "#8399A1",
          "ink-fainter": "#A6B6BC",
          accent: "#0E6274",
          "accent-hover": "#0A4A58",
          "accent-soft": "#EBF2F4",
          "accent-soft-border": "#B8D4DB",
          success: "#1F7A52",
          "success-soft": "#E4F0EA",
          "success-soft-border": "#A9CFBD",
          "success-dark": "#14563A",
          warn: "#9C5C0A",
          "warn-soft": "#FBF0DD",
          "warn-soft-border": "#E8D3A8",
          "warn-dark": "#7A480A",
          danger: "#8C3823",
          "danger-soft": "#F8E5E0",
          "danger-soft-border": "#DDBAB1",
          "internal-bg": "#0D171B",
        },
      },
      fontFamily: {
        figtree: ["Figtree_400Regular"],
        "figtree-medium": ["Figtree_500Medium"],
        "figtree-semibold": ["Figtree_600SemiBold"],
        "figtree-bold": ["Figtree_700Bold"],
        "figtree-extrabold": ["Figtree_800ExtraBold"],
        plex: ["IBMPlexSans_400Regular"],
        "plex-medium": ["IBMPlexSans_500Medium"],
        "plex-semibold": ["IBMPlexSans_600SemiBold"],
        "plex-bold": ["IBMPlexSans_700Bold"],
        mono: ["IBMPlexMono_400Regular"],
        "mono-medium": ["IBMPlexMono_500Medium"],
        "mono-semibold": ["IBMPlexMono_600SemiBold"],
      },
    },
  },
  plugins: [],
};
