"""add weeks_of_data to slot_stats

Revision ID: 00cccc104e8e
Revises: 1d0c6a6a6f92
Create Date: 2026-09-07 19:16:27.893749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00cccc104e8e'
down_revision: Union[str, None] = '1d0c6a6a6f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slot_stats', sa.Column('weeks_of_data', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slot_stats', 'weeks_of_data')
    # ### end Alembic commands ###
