"""add court cancellation policy fields

Revision ID: 19cf7e553535
Revises: 651abc777d2c
Create Date: 2026-09-20 21:03:36.618229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19cf7e553535'
down_revision: Union[str, None] = '651abc777d2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courts', sa.Column('cancellation_allowed', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('courts', sa.Column('cancellation_cutoff_hours', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courts', 'cancellation_cutoff_hours')
    op.drop_column('courts', 'cancellation_allowed')
    # ### end Alembic commands ###
