"""make waitlist uniqueness partial on is_active

Revision ID: 1d0c6a6a6f92
Revises: 59ea2d8b83e0
Create Date: 2026-09-07 18:49:27.715039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d0c6a6a6f92'
down_revision: Union[str, None] = '59ea2d8b83e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_waitlist'), 'waitlist', type_='unique')
    op.create_index('unique_active_waitlist', 'waitlist', ['court_id', 'player_id', 'slot_starts_at'], unique=True, postgresql_where=sa.text('is_active'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_active_waitlist', table_name='waitlist', postgresql_where=sa.text('is_active'))
    op.create_unique_constraint(op.f('unique_waitlist'), 'waitlist', ['court_id', 'player_id', 'slot_starts_at'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
