"""initial schema

Revision ID: 3059bec979b7
Revises: 
Create Date: 2026-09-07 13:57:08.182582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3059bec979b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_requests',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('otp_hash', sa.String(length=128), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_used', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_otp_phone', 'otp_requests', ['phone', 'created_at'], unique=False)
    op.create_table('users',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('player', 'owner', 'admin', name='user_role'), server_default='player', nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('reliability_score', sa.Numeric(precision=3, scale=2), server_default=sa.text('1.00'), nullable=False),
    sa.Column('total_bookings', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_no_shows', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('total_rejections', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.String(length=20), server_default=sa.text("'system'"), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_entity', 'audit_log', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_table('fcm_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('idx_fcm_user', 'fcm_tokens', ['user_id'], unique=False, postgresql_where=sa.text('is_active'))
    op.create_table('notification_log',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('template_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'sent'"), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('cost_category', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notif_cost', 'notification_log', ['cost_category', 'created_at'], unique=False)
    op.create_index('idx_notif_user', 'notification_log', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('revoked_reason', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_expires', 'sessions', ['expires_at'], unique=False, postgresql_where=sa.text('NOT is_revoked'))
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('venues',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('whatsapp', sa.String(length=20), nullable=True),
    sa.Column('sports', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('amenities', postgresql.ARRAY(sa.String(length=50)), nullable=True),
    sa.Column('photos', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('bank_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'changes_requested', 'rejected', name='venue_status'), server_default='pending', nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('auto_approve_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('auto_approve_min_bookings', sa.Integer(), server_default=sa.text('5'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # NOTE: GeoAlchemy2's DDL event listener already created the GIST index on
    # `location` (named idx_venues_location) as part of op.create_table above;
    # an explicit op.create_index here would collide with it.
    op.create_index('idx_venues_sports', 'venues', ['sports'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_venues_owner_id'), 'venues', ['owner_id'], unique=False)
    op.create_index(op.f('ix_venues_slug'), 'venues', ['slug'], unique=True)
    op.create_index(op.f('ix_venues_status'), 'venues', ['status'], unique=False)
    op.create_table('courts',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sport', sa.String(length=50), nullable=False),
    sa.Column('slot_minutes', sa.Integer(), server_default=sa.text('60'), nullable=False),
    sa.Column('surface_type', sa.String(length=50), nullable=True),
    sa.Column('is_indoor', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('has_floodlights', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courts_venue_id'), 'courts', ['venue_id'], unique=False)
    op.create_table('blackouts',
    sa.Column('court_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('starts_at < ends_at', name='valid_blackout'),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_blackouts_court_time', 'blackouts', ['court_id', 'starts_at', 'ends_at'], unique=False)
    op.create_table('bookings',
    sa.Column('court_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('held', 'payment_submitted', 'booked', 'completed', 'no_show', 'cancelled', name='booking_status'), server_default='held', nullable=False),
    sa.Column('source', sa.Enum('app', 'whatsapp', 'walkin', 'phone', name='booking_source'), server_default='app', nullable=False),
    sa.Column('player_name', sa.String(length=100), nullable=True),
    sa.Column('player_phone', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('advance_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('balance_due', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('held_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by', sa.Enum('player', 'owner', 'system', name='cancelled_by'), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bookings_court_time', 'bookings', ['court_id', 'starts_at'], unique=False)
    op.create_index('idx_bookings_held_expiry', 'bookings', ['held_until'], unique=False, postgresql_where=sa.text("status = 'held'"))
    op.create_index('idx_bookings_payment_deadline', 'bookings', ['payment_deadline'], unique=False, postgresql_where=sa.text("status = 'payment_submitted'"))
    op.create_index(op.f('ix_bookings_court_id'), 'bookings', ['court_id'], unique=False)
    op.create_index(op.f('ix_bookings_player_id'), 'bookings', ['player_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index('one_live_booking_per_slot', 'bookings', ['court_id', 'starts_at'], unique=True, postgresql_where=sa.text("status IN ('held', 'payment_submitted', 'booked')"))
    op.create_table('pricing_rules',
    sa.Column('court_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('day_of_week', postgresql.ARRAY(sa.SmallInteger()), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('price_per_slot', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('floodlight_surcharge', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('advance_percentage', sa.Numeric(precision=5, scale=2), server_default=sa.text('100.00'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pricing_court', 'pricing_rules', ['court_id', sa.literal_column('priority DESC')], unique=False)
    op.create_table('schedule_templates',
    sa.Column('court_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=False),
    sa.Column('close_time', sa.Time(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6', name='valid_day'),
    sa.CheckConstraint('open_time < close_time', name='valid_times'),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_schedule_court_day', 'schedule_templates', ['court_id', 'day_of_week'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_index(op.f('ix_schedule_templates_court_id'), 'schedule_templates', ['court_id'], unique=False)
    op.create_table('slot_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('court_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('hour', sa.SmallInteger(), nullable=False),
    sa.Column('total_slots', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('booked_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('booking_rate', sa.Numeric(precision=5, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('avg_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('computed_at', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('court_id', 'day_of_week', 'hour', 'computed_at', name='unique_stat')
    )
    op.create_index('idx_stats_court', 'slot_stats', ['court_id', 'computed_at'], unique=False)
    op.create_table('waitlist',
    sa.Column('court_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('slot_starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['court_id'], ['courts.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('court_id', 'player_id', 'slot_starts_at', name='unique_waitlist')
    )
    op.create_index('idx_waitlist_slot', 'waitlist', ['court_id', 'slot_starts_at'], unique=False, postgresql_where=sa.text('is_active'))
    op.create_table('messages',
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('sender_type', sa.String(length=20), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=20), server_default=sa.text("'text'"), nullable=False),
    sa.Column('whatsapp_msg_id', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_booking', 'messages', ['booking_id', 'created_at'], unique=False)
    op.create_index('idx_messages_venue', 'messages', ['venue_id', 'created_at'], unique=False)
    op.create_table('payments',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('proof_key', sa.String(length=500), nullable=True),
    sa.Column('proof_hash', sa.String(length=128), nullable=True),
    sa.Column('amount_claimed', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ocr_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ocr_ref', sa.String(length=100), nullable=True),
    sa.Column('ocr_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ocr_verdict', sa.String(length=20), nullable=True),
    sa.Column('ocr_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('ocr_raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_duplicate', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('duplicate_of', sa.UUID(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('review_verdict', sa.String(length=20), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_approved', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['duplicate_of'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_index(op.f('ix_payments_proof_hash'), 'payments', ['proof_hash'], unique=False)
    op.create_table('reviews',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('owner_reply', sa.Text(), nullable=True),
    sa.Column('owner_replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='valid_rating'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_index('idx_reviews_venue', 'reviews', ['venue_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reviews_venue', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_payments_proof_hash'), table_name='payments')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index('idx_messages_venue', table_name='messages')
    op.drop_index('idx_messages_booking', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_waitlist_slot', table_name='waitlist', postgresql_where=sa.text('is_active'))
    op.drop_table('waitlist')
    op.drop_index('idx_stats_court', table_name='slot_stats')
    op.drop_table('slot_stats')
    op.drop_index(op.f('ix_schedule_templates_court_id'), table_name='schedule_templates')
    op.drop_index('idx_schedule_court_day', table_name='schedule_templates', postgresql_where=sa.text('is_active'))
    op.drop_table('schedule_templates')
    op.drop_index('idx_pricing_court', table_name='pricing_rules')
    op.drop_table('pricing_rules')
    op.drop_index('one_live_booking_per_slot', table_name='bookings', postgresql_where=sa.text("status IN ('held', 'payment_submitted', 'booked')"))
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_player_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_court_id'), table_name='bookings')
    op.drop_index('idx_bookings_payment_deadline', table_name='bookings', postgresql_where=sa.text("status = 'payment_submitted'"))
    op.drop_index('idx_bookings_held_expiry', table_name='bookings', postgresql_where=sa.text("status = 'held'"))
    op.drop_index('idx_bookings_court_time', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index('idx_blackouts_court_time', table_name='blackouts')
    op.drop_table('blackouts')
    op.drop_index(op.f('ix_courts_venue_id'), table_name='courts')
    op.drop_table('courts')
    op.drop_index(op.f('ix_venues_status'), table_name='venues')
    op.drop_index(op.f('ix_venues_slug'), table_name='venues')
    op.drop_index(op.f('ix_venues_owner_id'), table_name='venues')
    op.drop_index('idx_venues_sports', table_name='venues', postgresql_using='gin')
    # GeoAlchemy2's DDL event listener drops the spatial index automatically
    # as part of op.drop_table below.
    op.drop_table('venues')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_index('idx_sessions_expires', table_name='sessions', postgresql_where=sa.text('NOT is_revoked'))
    op.drop_table('sessions')
    op.drop_index('idx_notif_user', table_name='notification_log')
    op.drop_index('idx_notif_cost', table_name='notification_log')
    op.drop_table('notification_log')
    op.drop_index('idx_fcm_user', table_name='fcm_tokens', postgresql_where=sa.text('is_active'))
    op.drop_table('fcm_tokens')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_index('idx_audit_entity', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_index('idx_otp_phone', table_name='otp_requests')
    op.drop_table('otp_requests')
    # ### end Alembic commands ###

    # Alembic's autogenerate doesn't emit DROP TYPE for enum columns (it can't
    # safely tell if another table still references the type), so drop them
    # explicitly here now that every table using them is gone.
    bind = op.get_bind()
    for enum_name in ('user_role', 'venue_status', 'booking_status', 'booking_source', 'cancelled_by'):
        postgresql.ENUM(name=enum_name).drop(bind, checkfirst=True)
