"""make messages venue_id nullable and dedupe whatsapp_msg_id

Revision ID: 59ea2d8b83e0
Revises: ca2c0190ac2a
Create Date: 2026-09-07 17:19:43.891893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59ea2d8b83e0'
down_revision: Union[str, None] = 'ca2c0190ac2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'venue_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('uq_messages_whatsapp_msg_id', 'messages', ['whatsapp_msg_id'], unique=True, postgresql_where=sa.text('whatsapp_msg_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_messages_whatsapp_msg_id', table_name='messages', postgresql_where=sa.text('whatsapp_msg_id IS NOT NULL'))
    op.alter_column('messages', 'venue_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
