"""add venue checkin_qr_token and booking checkin flag fields

Revision ID: 88c4d5be0fc4
Revises: 3a8b6d46ce30
Create Date: 2026-09-19 03:24:33.230225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88c4d5be0fc4'
down_revision: Union[str, None] = '3a8b6d46ce30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('checked_in_by', sa.String(length=20), nullable=True))
    op.add_column('bookings', sa.Column('checkin_flag_reason', sa.Text(), nullable=True))
    op.add_column('venues', sa.Column('checkin_qr_token', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.create_unique_constraint(None, 'venues', ['checkin_qr_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venues', type_='unique')
    op.drop_column('venues', 'checkin_qr_token')
    op.drop_column('bookings', 'checkin_flag_reason')
    op.drop_column('bookings', 'checked_in_by')
    # ### end Alembic commands ###
