"""add one_pending_payment_per_booking partial unique index

Revision ID: 92d8683004cf
Revises: 4838530927e1
Create Date: 2026-09-19 01:57:22.734555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d8683004cf'
down_revision: Union[str, None] = '4838530927e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('one_pending_payment_per_booking', 'payments', ['booking_id'], unique=True, postgresql_where=sa.text('review_verdict IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('one_pending_payment_per_booking', table_name='payments', postgresql_where=sa.text('review_verdict IS NULL'))
    # ### end Alembic commands ###
