"""add suspension_reason to users

Revision ID: b435865e71d8
Revises: 00cccc104e8e
Create Date: 2026-09-07 19:24:09.890074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b435865e71d8'
down_revision: Union[str, None] = '00cccc104e8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('suspension_reason', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'suspension_reason')
    # ### end Alembic commands ###
