"""add venue plan_tier

Revision ID: ca2c0190ac2a
Revises: 3059bec979b7
Create Date: 2026-09-07 16:44:27.463904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca2c0190ac2a'
down_revision: Union[str, None] = '3059bec979b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Unlike op.create_table, op.add_column on an existing table does not
    # auto-create a new enum type as a side effect -- do it explicitly first.
    plan_tier_enum = sa.Enum('free', 'pro', 'business', name='plan_tier')
    plan_tier_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('plan_tier', plan_tier_enum, server_default='free', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'plan_tier')
    # ### end Alembic commands ###

    from sqlalchemy.dialects import postgresql

    postgresql.ENUM(name='plan_tier').drop(op.get_bind(), checkfirst=True)
